name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Install dependencies
        run: npm install

  lint:
    runs-on: self-hosted
    needs: install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Run linting
        run: npm run lint

  test:
    runs-on: self-hosted
    needs: install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Run tests
        run: npm test

  build:
    runs-on: self-hosted
    needs: [install, test]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Restore node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      - name: Build project
        run: npm run build
