name: Code Validation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: self-hosted

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Cache node_modules
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: npm-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json', '**/package.json') }}
          restore-keys: |
            npm-cache-${{ runner.os }}-

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

  lint:
    runs-on: self-hosted
    needs: install

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Run linting
      - name: Run linter
        run: npm run lint

  test:
    runs-on: self-hosted
    needs: install

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Run tests
      - name: Run tests
        run: npm test

  build:
    runs-on: self-hosted
    needs: [install, test]

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      # Step 3: Build the project
      - name: Build project
        run: npm run build
